//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web;
namespace WebsiteQuanLyNhaAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class MonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonAn()
        {
            this.ChiTietNguyenLieux = new HashSet<ChiTietNguyenLieu>();
            this.ThucDons = new HashSet<ThucDon>();
            Images = "/Photos/20140305-austin-cheap-eats-primary.jpg";
        }

        [DisplayName("Mã Món Ăn")]
        [Required(ErrorMessage = "Vui lòng không để trống!!!")]
        public int MaMonAn { get; set; }
        [DisplayName("Tên Món Ăn")]
        [Required(ErrorMessage = "Vui lòng không để trống!!!")]
        public string TenMonAn { get; set; }
        [DisplayName("Loại Món Ăn")]
        [Required(ErrorMessage = "Vui lòng không để trống!!!")]
        public string LoaiMonAn { get; set; }
        [DisplayName("Đơn Giá")]
        [Required(ErrorMessage = "Vui lòng không để trống!!!")]
        public decimal DonGia { get; set; }
        [DisplayName("Hình Ảnh")]
        public string Images { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNguyenLieu> ChiTietNguyenLieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThucDon> ThucDons { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}
