//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyNhaAn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyNhaAnEntities : DbContext
    {
        public QuanLyNhaAnEntities()
            : base("name=QuanLyNhaAnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuaAn> BuaAns { get; set; }
        public virtual DbSet<ChiTietBuaAn> ChiTietBuaAns { get; set; }
        public virtual DbSet<ChiTietNguyenLieu> ChiTietNguyenLieux { get; set; }
        public virtual DbSet<MonAn> MonAns { get; set; }
        public virtual DbSet<NguyenLieu> NguyenLieux { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<ThanhToan> ThanhToans { get; set; }
        public virtual DbSet<ThanhToanNguyenLieu> ThanhToanNguyenLieux { get; set; }
        public virtual DbSet<ThucDon> ThucDons { get; set; }
    }
}
