//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyNhaAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int maNV { get; set; }
        public string tenNV { get; set; }
        public Nullable<decimal> gia { get; set; }
        public string thangan { get; set; }
        public string status { get; set; }
    }
}
