//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyNhaAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBuaAn
    {
        public int MaBuaAn { get; set; }
        public int MaMonAn { get; set; }
        public System.DateTime NgayAn { get; set; }
        public decimal DonGia { get; set; }
    
        public virtual BuaAn BuaAn { get; set; }
        public virtual ThucDon ThucDon { get; set; }
    }
}
