//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyNhaAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class NhanVien
    {
        [DisplayName("Mã Nhân Viên")]
        public int MaNV { get; set; }
        [DisplayName("Tên Nhân Viên")]
        public string TenNV { get; set; }
        [DisplayName("Số Điện Thoại")]
        public string SDT { get; set; }
        [DisplayName("Giới Tính")]
        public string GioiTinh { get; set; }
        public string CMND { get; set; }
        [DisplayName("Chức Vụ")]
        public string ChucVu { get; set; }
        public Nullable<int> CapChucVu { get; set; }
        public Nullable<int> TinhTrangTaiKhoan { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
