//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyNhaAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.BuaAns = new HashSet<BuaAn>();
        }

        [DisplayName("Mã Nhân Viên")]
        [Required(ErrorMessage = "Vui lòng nhập Mã Nhân Viên!!!")]
        public int MaNV { get; set; }
        [DisplayName("Mật Khẩu")]
        [Required(ErrorMessage = "Vui lòng nhập Mật Khẩu!!!")]
        [DataType(DataType.Password)]
        public string Pass { get; set; }

        public string LoginErrorMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuaAn> BuaAns { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
