//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyNhaAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


    public partial class ThanhToanNguyenLieu
    {
        [DisplayName("Mã Hóa Đơn")]
        public int MaHoaDonNguyenLieu { get; set; }
        [DisplayName("Giá Tiền")]
        public Nullable<decimal> GiaTien { get; set; }
        [DisplayName("Ngày")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        [DisplayName("Thứ")]
        public string ThuTrongTuan { get; set; }
    }
}
